version: "3.8"
services:
  user-service:
    build: .
    restart: always
    env_file: .env
    ports:
      - "8080:8080"
    networks:
      - app-db-network
    environment:
      SPRING_APPLICATION_JSON: '{
             "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/$MYSQLDB_DATABASE?useSSL=false",
             "spring.datasource.username" : "$MYSQLDB_USER",
             "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
             "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
             "spring.jpa.hibernate.ddl-auto" : "update"
           }'
    depends_on:
      - mysqldb

  mysqldb:
    image: "mysql:5.7"
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLDB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQLDB_DATABASE}
#      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
#      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      volumes:
#        - db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-db-network

networks:
  app-db-network:
volumes:
  db: